package com.yif.dao.mapper;

import com.yif.bean.Contact;

public interface ContactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insert(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insertSelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    Contact selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKeySelective(Contact record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_contact
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKey(Contact record);
}