package com.yif.dao.mapper;

import com.yif.bean.Image;

public interface ImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insert(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insertSelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    Image selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKeySelective(Image record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_image
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKey(Image record);
}