package com.yif.dao.mapper;

import com.yif.bean.Liveness;

public interface LivenessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insert(Liveness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int insertSelective(Liveness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    Liveness selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKeySelective(Liveness record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table y_liveness
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    int updateByPrimaryKey(Liveness record);
}