package com.yif.dao.web;

public interface WebConstants {
	String USER_SESSION_KEY = "USER_SESSION_KEY";
	
	//短信息中的验证码
	String SYS_SMS_CODE_SESSION_KEY = "SYS_SMS_CODE_SESSION_KEY";
	
	String ADMIN_SESSION_KEY = "ADMIN_SESSION_KEY";
	
	String USER_PWCHANGE_SESSION_KEY = "USER_PWCHANGE_SESSION_KEY";//用户手机密码修改
	
	String USER_PWCHANGE_EMAIL_SESSION_KEY = "USER_PWCHANGE_EMAIL_SESSION_KEY";//用户邮件密码修改
	
	//
	String SEARCH_CONDITION_KEY = "SEARCH_CONDITION_KEY";
	
	String SEARCH_CONDITION_PAGE_KEY = "SEARCH_CONDITION_PAGE_KEY";
}
