package com.yif.bean;

public class Comment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_comment.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_comment.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer mId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_comment.context
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String context;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_comment.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_comment.p_comment
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer pComment;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_comment.id
     *
     * @return the value of y_comment.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_comment.id
     *
     * @param id the value for y_comment.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_comment.m_id
     *
     * @return the value of y_comment.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_comment.m_id
     *
     * @param mId the value for y_comment.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_comment.context
     *
     * @return the value of y_comment.context
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_comment.context
     *
     * @param context the value for y_comment.context
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setContext(String context) {
        this.context = context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_comment.user_id
     *
     * @return the value of y_comment.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_comment.user_id
     *
     * @param userId the value for y_comment.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_comment.p_comment
     *
     * @return the value of y_comment.p_comment
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getpComment() {
        return pComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_comment.p_comment
     *
     * @param pComment the value for y_comment.p_comment
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setpComment(Integer pComment) {
        this.pComment = pComment;
    }
}