package com.yif.bean;

import java.util.Date;

public class Contact {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.c_name
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.c_phone
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String cPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.c_email
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String cEmail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_contact.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer mId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.id
     *
     * @return the value of y_contact.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.id
     *
     * @param id the value for y_contact.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.c_name
     *
     * @return the value of y_contact.c_name
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.c_name
     *
     * @param cName the value for y_contact.c_name
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setcName(String cName) {
        this.cName = cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.c_phone
     *
     * @return the value of y_contact.c_phone
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getcPhone() {
        return cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.c_phone
     *
     * @param cPhone the value for y_contact.c_phone
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setcPhone(String cPhone) {
        this.cPhone = cPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.c_email
     *
     * @return the value of y_contact.c_email
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getcEmail() {
        return cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.c_email
     *
     * @param cEmail the value for y_contact.c_email
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setcEmail(String cEmail) {
        this.cEmail = cEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.addtime
     *
     * @return the value of y_contact.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.addtime
     *
     * @param addtime the value for y_contact.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_contact.m_id
     *
     * @return the value of y_contact.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getmId() {
        return mId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_contact.m_id
     *
     * @param mId the value for y_contact.m_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setmId(Integer mId) {
        this.mId = mId;
    }
}