package com.yif.bean;

import java.util.Date;

public class Liveness {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_liveness.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_liveness.i_persons
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer iPersons;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_liveness.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_liveness.id
     *
     * @return the value of y_liveness.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_liveness.id
     *
     * @param id the value for y_liveness.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_liveness.i_persons
     *
     * @return the value of y_liveness.i_persons
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getiPersons() {
        return iPersons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_liveness.i_persons
     *
     * @param iPersons the value for y_liveness.i_persons
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setiPersons(Integer iPersons) {
        this.iPersons = iPersons;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_liveness.addtime
     *
     * @return the value of y_liveness.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_liveness.addtime
     *
     * @param addtime the value for y_liveness.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}