package com.yif.bean;

import java.util.Date;

public class Mrelease {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.y_u_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer yUId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.title
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.key_word
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String keyWord;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.content
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.m_address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String mAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.isshow
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer isshow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.assist
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer assist;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.type
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.price
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Date addtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column m_release_info.ext2
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String ext2;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.id
     *
     * @return the value of m_release_info.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.id
     *
     * @param id the value for m_release_info.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.y_u_id
     *
     * @return the value of m_release_info.y_u_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getyUId() {
        return yUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.y_u_id
     *
     * @param yUId the value for m_release_info.y_u_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setyUId(Integer yUId) {
        this.yUId = yUId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.title
     *
     * @return the value of m_release_info.title
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.title
     *
     * @param title the value for m_release_info.title
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.key_word
     *
     * @return the value of m_release_info.key_word
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getKeyWord() {
        return keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.key_word
     *
     * @param keyWord the value for m_release_info.key_word
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setKeyWord(String keyWord) {
        this.keyWord = keyWord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.content
     *
     * @return the value of m_release_info.content
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.content
     *
     * @param content the value for m_release_info.content
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.m_address
     *
     * @return the value of m_release_info.m_address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getmAddress() {
        return mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.m_address
     *
     * @param mAddress the value for m_release_info.m_address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setmAddress(String mAddress) {
        this.mAddress = mAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.isshow
     *
     * @return the value of m_release_info.isshow
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.isshow
     *
     * @param isshow the value for m_release_info.isshow
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.assist
     *
     * @return the value of m_release_info.assist
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getAssist() {
        return assist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.assist
     *
     * @param assist the value for m_release_info.assist
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAssist(Integer assist) {
        this.assist = assist;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.type
     *
     * @return the value of m_release_info.type
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.type
     *
     * @param type the value for m_release_info.type
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.price
     *
     * @return the value of m_release_info.price
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.price
     *
     * @param price the value for m_release_info.price
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.addtime
     *
     * @return the value of m_release_info.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.addtime
     *
     * @param addtime the value for m_release_info.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.ext1
     *
     * @return the value of m_release_info.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.ext1
     *
     * @param ext1 the value for m_release_info.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column m_release_info.ext2
     *
     * @return the value of m_release_info.ext2
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getExt2() {
        return ext2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column m_release_info.ext2
     *
     * @param ext2 the value for m_release_info.ext2
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setExt2(String ext2) {
        this.ext2 = ext2;
    }
}