package com.yif.bean;

import java.util.Date;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_role.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_role.rolename
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String rolename;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_role.remark
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_role.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String ext1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_role.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_role.id
     *
     * @return the value of y_role.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_role.id
     *
     * @param id the value for y_role.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_role.rolename
     *
     * @return the value of y_role.rolename
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getRolename() {
        return rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_role.rolename
     *
     * @param rolename the value for y_role.rolename
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_role.remark
     *
     * @return the value of y_role.remark
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_role.remark
     *
     * @param remark the value for y_role.remark
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_role.ext1
     *
     * @return the value of y_role.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getExt1() {
        return ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_role.ext1
     *
     * @param ext1 the value for y_role.ext1
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setExt1(String ext1) {
        this.ext1 = ext1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_role.addtime
     *
     * @return the value of y_role.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_role.addtime
     *
     * @param addtime the value for y_role.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}