package com.yif.bean;

import java.util.Date;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.realname
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String realname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.idcard
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String idcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.age
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.sex
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.province
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.city
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.county
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String county;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.birthdate
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private String birthdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column y_userinfo.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.id
     *
     * @return the value of y_userinfo.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.id
     *
     * @param id the value for y_userinfo.id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.realname
     *
     * @return the value of y_userinfo.realname
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getRealname() {
        return realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.realname
     *
     * @param realname the value for y_userinfo.realname
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setRealname(String realname) {
        this.realname = realname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.idcard
     *
     * @return the value of y_userinfo.idcard
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getIdcard() {
        return idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.idcard
     *
     * @param idcard the value for y_userinfo.idcard
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setIdcard(String idcard) {
        this.idcard = idcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.age
     *
     * @return the value of y_userinfo.age
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.age
     *
     * @param age the value for y_userinfo.age
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.sex
     *
     * @return the value of y_userinfo.sex
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.sex
     *
     * @param sex the value for y_userinfo.sex
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.address
     *
     * @return the value of y_userinfo.address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.address
     *
     * @param address the value for y_userinfo.address
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.province
     *
     * @return the value of y_userinfo.province
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.province
     *
     * @param province the value for y_userinfo.province
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.city
     *
     * @return the value of y_userinfo.city
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.city
     *
     * @param city the value for y_userinfo.city
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.county
     *
     * @return the value of y_userinfo.county
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getCounty() {
        return county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.county
     *
     * @param county the value for y_userinfo.county
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setCounty(String county) {
        this.county = county;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.user_id
     *
     * @return the value of y_userinfo.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.user_id
     *
     * @param userId the value for y_userinfo.user_id
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.birthdate
     *
     * @return the value of y_userinfo.birthdate
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.birthdate
     *
     * @param birthdate the value for y_userinfo.birthdate
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column y_userinfo.addtime
     *
     * @return the value of y_userinfo.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column y_userinfo.addtime
     *
     * @param addtime the value for y_userinfo.addtime
     *
     * @mbggenerated Sat Apr 16 15:30:57 CST 2016
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}